package hibernaterecu;
// Generated 14-abr-2020 16:29:37 by Hibernate Tools 4.3.1



/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer idPersonal;
     private String nombre;
     private String apellidos;
     private int telefono;
     private String seccion;

    public Personal() {
    }

    public Personal(String nombre, String apellidos, int telefono, String seccion) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.seccion = seccion;
    }
   
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }




}


